name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Navigate to project folder
        run: cd DomainSpaceFrontend

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build:production

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "Deploying to the VPS..."
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./DomainSpaceFrontend/build/* ${{ secrets.SSH_USER }}@${{ secrets.VPS_IP }}:/var/www/${{ secrets.REACT_FOLDER_NAME }}

      - name: Reload Nginx
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "Reloading Nginx on the VPS..."
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VPS_IP }} << EOF
            sudo systemctl reload nginx
          EOF
